---
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-api-keys
  namespace: media
data:
  radarr-api-key: "fa15aa8c601345308478b355e0fe9079"
  sonarr-api-key: "fc32a82594b0416d8e2cf8cb14729265"
  prowlarr-api-key: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      nodeSelector:
        node-role.home.lab/compute: "true"
      initContainers:
      - name: create-config
        image: busybox:latest
        command: ['sh', '-c', 'mkdir -p /config && chown -R 1000:1000 /config']
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        ports:
        - containerPort: 9696
          name: http
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Toronto"
        - name: UMASK
          value: "002"
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: prowlarr
  ports:
  - port: 9696
    targetPort: 9696
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - prowlarr.home.lab
    secretName: prowlarr-tls
  rules:
  - host: prowlarr.home.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 9696