---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>K3s Demo - LoadBalancer</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
            }
            .container { 
                text-align: center;
                padding: 2rem;
                background: rgba(255,255,255,0.1);
                border-radius: 10px;
                backdrop-filter: blur(10px);
            }
            h1 { font-size: 3rem; margin-bottom: 1rem; }
            .info { 
                background: rgba(0,0,0,0.2);
                padding: 1rem;
                border-radius: 5px;
                margin-top: 1rem;
            }
            .pod-name { color: #ffd700; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 K3s + MetalLB Demo</h1>
            <p>This page is served by NGINX running on Kubernetes</p>
            <div class="info">
                <p>✅ LoadBalancer Service Type</p>
                <p>✅ MetalLB IP Assignment</p>
                <p>✅ 3 Replica Pods</p>
                <p class="pod-name">Pod: HOSTNAME</p>
            </div>
        </div>
        <script>
            fetch('/hostname')
                .then(r => r.text())
                .then(h => document.querySelector('.pod-name').textContent = 'Pod: ' + h)
                .catch(() => {});
        </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: nginx-demo
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP