---
- name: Create metallb-system namespace
  kubernetes.core.k8s:
    name: metallb-system
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Apply MetalLB manifest
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Wait for MetalLB controller
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: controller
    namespace: metallb-system
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: controller_deployment
  until: controller_deployment.resources[0].status.readyReplicas | default(0) > 0
  retries: 60
  delay: 5

- name: Wait for MetalLB speaker
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: DaemonSet
    name: speaker
    namespace: metallb-system
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: speaker_daemonset
  until: speaker_daemonset.resources[0].status.numberReady | default(0) > 0
  retries: 60
  delay: 5

- name: Create IPAddressPool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: home-pool
        namespace: metallb-system
      spec:
        addresses:
          - "{{ metallb_ip_range }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Create L2Advertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: home-l2
        namespace: metallb-system
      spec:
        ipAddressPools:
          - home-pool
    kubeconfig: /etc/rancher/k3s/k3s.yaml