---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-pvc
  namespace: cloud-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: cloud-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      nodeSelector:
        node-role.home.lab/compute: "true"
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:latest
        ports:
        - containerPort: 9000
          name: http
        env:
        - name: ALLOW_SIGNUP
          value: "true"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Toronto"
        - name: MAX_WORKERS
          value: "1"
        - name: WEB_CONCURRENCY
          value: "1"
        - name: BASE_URL
          value: "https://mealie.home.lab"
        - name: DB_ENGINE
          value: "sqlite"
        - name: DEFAULT_GROUP
          value: "Home"
        volumeMounts:
        - name: app-data
          mountPath: /app/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: mealie-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: cloud-services
spec:
  type: LoadBalancer
  selector:
    app: mealie
  ports:
  - port: 9000
    targetPort: 9000
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  namespace: cloud-services
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - mealie.home.lab
    secretName: mealie-tls
  rules:
  - host: mealie.home.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mealie
            port:
              number: 9000