---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - vim
      - git
      - htop
      - net-tools
      - ca-certificates
      - gnupg
      - lsb-release
      - software-properties-common
      - apt-transport-https
      - python3-pip
      - ntp
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    state: absent

- name: Create k8s directory
  file:
    path: /root/k8s
    state: directory
    mode: '0755'

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Persist kernel modules
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf

- name: Set sysctl parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'fs.inotify.max_user_watches', value: '524288' }
    - { key: 'fs.inotify.max_user_instances', value: '512' }