---
cluster_domain: home.lab
timezone: America/Toronto
k3s_version: v1.31.3+k3s1
k3s_token: "supersecrettoken123"
metallb_version: v0.14.9
metallb_ip_range: 172.23.25.240-172.23.25.250
cert_manager_version: v1.14.5
ca_common_name: "Home Lab CA"
ca_country: "CA"
ca_state: "ON"
ca_locality: "Toronto"
ca_organization: "Home Lab"
ca_organizational_unit: "IT"
ca_email: "admin@home.lab"